$("#button").click(function()
{
    $.ajax(
        {
            url:"load2.html",
            statusCode:
            {
                404:function()
                    {
                        $("#content").text("Page not found");
                    }
            },
            success:function(data)
            {
                $("#content").html(data)
            }
        }
    )
})